//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCodeSender.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string SerialPortName {
            get {
                return ((string)(this["SerialPortName"]));
            }
            set {
                this["SerialPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115200")]
        public int SerialPortBaud {
            get {
                return ((int)(this["SerialPortBaud"]));
            }
            set {
                this["SerialPortBaud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Serial")]
        public global::GCodeSender.Communication.ConnectionType ConnectionType {
            get {
                return ((global::GCodeSender.Communication.ConnectionType)(this["ConnectionType"]));
            }
            set {
                this["ConnectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public int ControllerBufferSize {
            get {
                return ((int)(this["ControllerBufferSize"]));
            }
            set {
                this["ControllerBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatusPollInterval {
            get {
                return ((int)(this["StatusPollInterval"]));
            }
            set {
                this["StatusPollInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ViewportArcSplit {
            get {
                return ((double)(this["ViewportArcSplit"]));
            }
            set {
                this["ViewportArcSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCodePreview {
            get {
                return ((bool)(this["EnableCodePreview"]));
            }
            set {
                this["EnableCodePreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ProbeSafeHeight {
            get {
                return ((double)(this["ProbeSafeHeight"]));
            }
            set {
                this["ProbeSafeHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ProbeMaxDepth {
            get {
                return ((double)(this["ProbeMaxDepth"]));
            }
            set {
                this["ProbeMaxDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AbortOnProbeFail {
            get {
                return ((bool)(this["AbortOnProbeFail"]));
            }
            set {
                this["AbortOnProbeFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double ProbeFeed {
            get {
                return ((double)(this["ProbeFeed"]));
            }
            set {
                this["ProbeFeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ArcToLineSegmentLength {
            get {
                return ((double)(this["ArcToLineSegmentLength"]));
            }
            set {
                this["ArcToLineSegmentLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double SplitSegmentLength {
            get {
                return ((double)(this["SplitSegmentLength"]));
            }
            set {
                this["SplitSegmentLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public int WebServerPort {
            get {
                return ((int)(this["WebServerPort"]));
            }
            set {
                this["WebServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double JogFeedX {
            get {
                return ((double)(this["JogFeedX"]));
            }
            set {
                this["JogFeedX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogDistanceX {
            get {
                return ((double)(this["JogDistanceX"]));
            }
            set {
                this["JogDistanceX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogTraffic {
            get {
                return ((bool)(this["LogTraffic"]));
            }
            set {
                this["LogTraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GCodeIncludeSpindle {
            get {
                return ((bool)(this["GCodeIncludeSpindle"]));
            }
            set {
                this["GCodeIncludeSpindle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GCodeIncludeDwell {
            get {
                return ((bool)(this["GCodeIncludeDwell"]));
            }
            set {
                this["GCodeIncludeDwell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GCodeIncludeMEnd {
            get {
                return ((bool)(this["GCodeIncludeMEnd"]));
            }
            set {
                this["GCodeIncludeMEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PauseFileOnHold {
            get {
                return ((bool)(this["PauseFileOnHold"]));
            }
            set {
                this["PauseFileOnHold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowStatusLines {
            get {
                return ((bool)(this["ShowStatusLines"]));
            }
            set {
                this["ShowStatusLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ConsoleFadeTime {
            get {
                return ((double)(this["ConsoleFadeTime"]));
            }
            set {
                this["ConsoleFadeTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ToolLengthSetterPos {
            get {
                return ((double)(this["ToolLengthSetterPos"]));
            }
            set {
                this["ToolLengthSetterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SettingsSendDelay {
            get {
                return ((int)(this["SettingsSendDelay"]));
            }
            set {
                this["SettingsSendDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpdateRequired {
            get {
                return ((bool)(this["SettingsUpdateRequired"]));
            }
            set {
                this["SettingsUpdateRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TLSUseActualPos {
            get {
                return ((bool)(this["TLSUseActualPos"]));
            }
            set {
                this["TLSUseActualPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManualUseExpressions {
            get {
                return ((bool)(this["ManualUseExpressions"]));
            }
            set {
                this["ManualUseExpressions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileExpanderOpen {
            get {
                return ((bool)(this["FileExpanderOpen"]));
            }
            set {
                this["FileExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditExpanderOpen {
            get {
                return ((bool)(this["EditExpanderOpen"]));
            }
            set {
                this["EditExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverrideExpanderOpen {
            get {
                return ((bool)(this["OverrideExpanderOpen"]));
            }
            set {
                this["OverrideExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProbingExpanderOpen {
            get {
                return ((bool)(this["ProbingExpanderOpen"]));
            }
            set {
                this["ProbingExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManualExpanderOpen {
            get {
                return ((bool)(this["ManualExpanderOpen"]));
            }
            set {
                this["ManualExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManualProbingExpanderOpen {
            get {
                return ((bool)(this["ManualProbingExpanderOpen"]));
            }
            set {
                this["ManualProbingExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MacroExpanderOpen {
            get {
                return ((bool)(this["MacroExpanderOpen"]));
            }
            set {
                this["MacroExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MachineExpanderOpen {
            get {
                return ((bool)(this["MachineExpanderOpen"]));
            }
            set {
                this["MachineExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AboutExpanderOpen {
            get {
                return ((bool)(this["AboutExpanderOpen"]));
            }
            set {
                this["AboutExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugExpanderOpen {
            get {
                return ((bool)(this["DebugExpanderOpen"]));
            }
            set {
                this["DebugExpanderOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableEscapeSoftReset {
            get {
                return ((bool)(this["EnableEscapeSoftReset"]));
            }
            set {
                this["EnableEscapeSoftReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IgnoreAdditionalAxes {
            get {
                return ((bool)(this["IgnoreAdditionalAxes"]));
            }
            set {
                this["IgnoreAdditionalAxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float GridThickness {
            get {
                return ((float)(this["GridThickness"]));
            }
            set {
                this["GridThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SerialPortDTR {
            get {
                return ((bool)(this["SerialPortDTR"]));
            }
            set {
                this["SerialPortDTR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50;-150;250;-50;150;-250")]
        public string ViewPortPos {
            get {
                return ((string)(this["ViewPortPos"]));
            }
            set {
                this["ViewPortPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Probe and set Zero:G38.2Z-10F20\r\nG92Z0;")]
        public string Macros {
            get {
                return ((string)(this["Macros"]));
            }
            set {
                this["Macros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float ProbeTouchPlateThickness {
            get {
                return ((float)(this["ProbeTouchPlateThickness"]));
            }
            set {
                this["ProbeTouchPlateThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeedRateIncrement {
            get {
                return ((bool)(this["FeedRateIncrement"]));
            }
            set {
                this["FeedRateIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpindleIncrement {
            get {
                return ((bool)(this["SpindleIncrement"]));
            }
            set {
                this["SpindleIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowWarningWindow {
            get {
                return ((bool)(this["ShowWarningWindow"]));
            }
            set {
                this["ShowWarningWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelRapidColor {
            get {
                return ((string)(this["ModelRapidColor"]));
            }
            set {
                this["ModelRapidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelLineColor {
            get {
                return ((string)(this["ModelLineColor"]));
            }
            set {
                this["ModelLineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModelArcColor {
            get {
                return ((string)(this["ModelArcColor"]));
            }
            set {
                this["ModelArcColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogDistanceY {
            get {
                return ((double)(this["JogDistanceY"]));
            }
            set {
                this["JogDistanceY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double JogFeedY {
            get {
                return ((double)(this["JogFeedY"]));
            }
            set {
                this["JogFeedY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogDistanceZ {
            get {
                return ((double)(this["JogDistanceZ"]));
            }
            set {
                this["JogDistanceZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double JogFeedZ {
            get {
                return ((double)(this["JogFeedZ"]));
            }
            set {
                this["JogFeedZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogFeedXIncDec {
            get {
                return ((double)(this["JogFeedXIncDec"]));
            }
            set {
                this["JogFeedXIncDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogFeedYIncDec {
            get {
                return ((double)(this["JogFeedYIncDec"]));
            }
            set {
                this["JogFeedYIncDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogFeedZIncDec {
            get {
                return ((double)(this["JogFeedZIncDec"]));
            }
            set {
                this["JogFeedZIncDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogDistXIncDec {
            get {
                return ((double)(this["JogDistXIncDec"]));
            }
            set {
                this["JogDistXIncDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogDistYIncDec {
            get {
                return ((double)(this["JogDistYIncDec"]));
            }
            set {
                this["JogDistYIncDec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double JogDistZIncDec {
            get {
                return ((double)(this["JogDistZIncDec"]));
            }
            set {
                this["JogDistZIncDec"] = value;
            }
        }
    }
}
